---
# ConfigMap con la app web simple
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-simple-app
  namespace: logistica-system
data:
  app.py: |
    from flask import Flask, render_template_string
    import os
    import redis
    import json

    app = Flask(__name__)

    REDIS_HOST = os.getenv("REDIS_HOST", "redis-service")
    REDIS_PORT = int(os.getenv("REDIS_PORT", "6379"))
    REDIS_PASSWORD = os.getenv("REDIS_PASSWORD", "")
    LIST_KEY = os.getenv("LIST_KEY", "sensor:data")
    LIMIT = int(os.getenv("LIMIT", "50"))

    r = redis.Redis(
        host=REDIS_HOST,
        port=REDIS_PORT,
        password=REDIS_PASSWORD,
        decode_responses=True,
        socket_timeout=5,
        socket_connect_timeout=5,
    )

    TEMPLATE = """
    <!doctype html>
    <html lang="es">
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>Monitoreo de Sensores</title>
      <meta http-equiv="refresh" content="3" />
      <style>
        body { font-family: Arial, sans-serif; margin: 24px; background: #f5f6f8; }
        h1 { margin-bottom: 8px; }
        .meta { color: #666; margin-bottom: 16px; }
        table { width: 100%; border-collapse: collapse; background: #fff; }
        th, td { padding: 8px 10px; border-bottom: 1px solid #eee; text-align: left; }
        th { background: #fafafa; }
        .empty { color: #888; }
      </style>
    </head>
    <body>
      <h1>Monitoreo de Sensores</h1>
      <div class="meta">Actualiza cada 3s • Clave: {{ list_key }} • Últimos {{ limit }} registros</div>
      {% if rows %}
      <table>
        <thead>
          <tr>
            <th>Sensor</th>
            <th>Valor</th>
            <th>Timestamp</th>
          </tr>
        </thead>
        <tbody>
          {% for row in rows %}
          <tr>
            <td>{{ row.sensor_id }}</td>
            <td>{{ row.valor }}</td>
            <td>{{ row.timestamp }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% else %}
        <div class="empty">Sin datos todavía.</div>
      {% endif %}
    </body>
    </html>
    """

    @app.route("/")
    def index():
        try:
            items = r.lrange(LIST_KEY, 0, LIMIT - 1)
            rows = [json.loads(x) for x in items]
        except Exception:
            rows = []
        return render_template_string(TEMPLATE, rows=rows, list_key=LIST_KEY, limit=LIMIT)

    if __name__ == "__main__":
        app.run(host="0.0.0.0", port=8080)

---
# Deployment del cliente web simple
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-simple
  namespace: logistica-system
  labels:
    app: web-simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-simple
  template:
    metadata:
      labels:
        app: web-simple
    spec:
      containers:
      - name: web-simple
        image: python:3.11-alpine
        command:
        - sh
        - -c
        - |
          pip install --no-cache-dir flask redis
          python /app/app.py
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: redis-password
        - name: LIST_KEY
          value: "sensor:data"
        - name: LIMIT
          value: "50"
        volumeMounts:
        - name: app
          mountPath: /app
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: app
        configMap:
          name: web-simple-app
          defaultMode: 0755

---
# Service del cliente web simple
apiVersion: v1
kind: Service
metadata:
  name: web-simple-service
  namespace: logistica-system
  labels:
    app: web-simple
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30081
    protocol: TCP
    name: http
  selector:
    app: web-simple
